### ISSUE TITLE
Is there a way to make Ignition work on an iPad 2?

### ISSUE THREAD

**Issue by treyrutledge** [b3ll/Ignition#32] opened 2014-12-30 16:39 UTC
When trying to use ignition on an iPad 2 it will not let you because the iPad 2 does not have Siri on it. Would it be possible to bypass this Siri check in the program and make it load as normal?

**Comment by b3ll** [comment] 2015-01-03 19:54
dupe of #33

**Closed by b3ll** 2015-01-03 19:54 UTC
Labels: wontfix
